theme: jekyll-theme-cayman

title: Video saliency detection algorithm based on spatial-temporal information
description: A novel spatial-temporal information based saliency detection method proposed for high-performance salient object detection in video.  <br />
